import './styles.css';
import heroArt from './assets/renewal-board.webp';
import { addDays, allOccurrences, icsReminders, money, sampleSubscriptions, type Decision, type Frequency, type Occurrence, type Subscription } from './domain';
import { clearSubscriptions, readSubscriptions, saveSubscriptions } from './storage';

const app = document.querySelector<HTMLDivElement>('#app')!;
const today = new Date().toISOString().slice(0, 10);
let items: Subscription[] = [];
let isDemo = location.pathname === '/demo' || new URLSearchParams(location.search).get('demo') === '1';
let removed: Subscription | undefined;
let currentRoute = location.pathname;
let notice = '';
let firstRender = true;
const space = () => isDemo ? 'demo:subscriptions' : 'real:subscriptions';
const esc = (value = '') => value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]!));
const fmtDate = (date: string) => new Intl.DateTimeFormat(undefined, { weekday: 'short', month: 'short', day: 'numeric', timeZone: 'UTC' }).format(new Date(`${date}T12:00:00Z`));
const relative = (day: string) => { const value = Math.round((Date.parse(`${day}T12:00:00Z`) - Date.parse(`${today}T12:00:00Z`)) / 86_400_000); return value === 0 ? 'today' : value === 1 ? 'tomorrow' : value > 1 ? `in ${value} days` : `${Math.abs(value)} days ago`; };
const download = (name: string, data: string, type: string) => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([data], { type })); a.download = name; a.click(); URL.revokeObjectURL(a.href); };

function header() {
  return `<header class="site-header"><a class="wordmark" href="/" data-route>RENEWAL<br>LEDGER<span>™</span></a><nav aria-label="Main navigation"><a href="/demo" data-route>Demo</a><a href="/app" data-route>Calendar</a><a href="/privacy" data-route>Privacy</a></nav></header>`;
}
function footer() { return `<footer><p>Local renewal dates, with a human attached.</p><p><a href="/privacy" data-route>Privacy</a> · <a href="/terms" data-route>Terms</a> · Built by Param Factory · v1.0.0</p></footer>`; }
function demoBanner() { return isDemo ? `<aside class="demo-banner" aria-label="Demo mode"><strong>Demo</strong> — sample data, nothing is saved.<button class="link-button" id="reset-demo">Reset demo</button><button class="link-button" id="start-real">Start for real</button></aside>` : ''; }

function landing() {
  document.title = 'Subscription Renewal Calendar — see renewals';
  return `${header()}<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow">OFFLINE RENEWAL CONTROL</p><h1>See renewals before they charge.</h1><p class="lede">For small teams that need a cost, owner, and decision before every recurring charge.</p><div class="hero-actions"><a class="button primary" href="/demo" data-route>Try it with sample data</a><span>Loads a working 60-day calendar.</span></div><ul class="facts"><li>Runs on this device</li><li>Exports calendar reminders</li><li>$19 once for Pro forecasts</li></ul></div><figure class="hero-art"><img src="${heroArt}" width="1200" height="800" fetchpriority="high" decoding="async" alt="A blank paper renewal calendar with invoices and colored decision tabs." /><figcaption>Generated original art. Your entries stay on your device.</figcaption></figure></section><section class="preview-section" aria-labelledby="preview-title"><div><p class="eyebrow">THE DECISION LIST</p><h2 id="preview-title">A date without an owner is not a plan.</h2></div>${samplePreview()}</section><section class="how" aria-labelledby="how-title"><h2 id="how-title">How the renewal calendar works</h2><ol><li><strong>Import your list.</strong> Bring a CSV, or add the first charge by hand.</li><li><strong>Name an owner.</strong> Add a review date before each charge.</li><li><strong>Decide in time.</strong> Export reminders or mark it keep, review, or cancel.</li></ol></section><section class="privacy-note" aria-labelledby="privacy-title"><h2 id="privacy-title">What this does not do</h2><p>It does not connect to your bank, move money, or send your subscriptions elsewhere. You control the exports and can delete everything.</p></section><section class="pro" aria-labelledby="pro-title"><p class="eyebrow">OPTIONAL ONE-TIME UPGRADE</p><h2 id="pro-title">Plan farther ahead with Pro.</h2><p>Pro costs $19 once. It adds a 12-month forecast and annual cost view. Core tracking, CSV, ICS, encrypted backups, and deletion stay free.</p><a class="button" href="https://api.sociobot.in/api/v1/products/subscription-renewal-calendar/checkout">Buy Pro for $19</a> <a href="/app" data-route>Restore a license in the calendar</a></section></main>${footer()}`;
}
function samplePreview() { const due = allOccurrences(sampleSubscriptions(), today, addDays(today, 30)).slice(0, 4); return `<div class="mini-ledger">${due.map((x) => `<div><b>${esc(x.name)}</b><span>${fmtDate(x.dueOn)}</span><span>${money(x.amount, x.currency)}</span><em>${esc(x.owner)}</em></div>`).join('')}</div>`; }
function appView() {
  document.title = isDemo ? 'Demo — Subscription Renewal Calendar' : 'Calendar — Subscription Renewal Calendar';
  const through = addDays(today, 60); const occurrences = allOccurrences(items, today, through); const dueSoon = occurrences.filter((o) => o.reviewOn <= today && o.decision === 'review');
  return `${header()}${demoBanner()}<main id="main" class="app-main"><section class="app-heading"><div><p class="eyebrow">${isDemo ? 'SAMPLE WORKSPACE' : 'YOUR RENEWAL BOARD'}</p><h1>Your next 60 days of renewals</h1><p class="lede">Every occurrence is shown, including weekly charges in the same month.</p></div><div class="summary" aria-label="Calendar summary"><b>${money(occurrences.reduce((sum, x) => sum + x.amount, 0), occurrences[0]?.currency || 'USD')}</b><span>scheduled in 60 days</span><b>${new Set(items.map((x) => x.owner).filter(Boolean)).size}</b><span>owners named</span></div></section>${notice ? `<p class="notice" role="status">${esc(notice)}${removed ? ' <button class="link-button" id="undo-delete">Undo</button>' : ''}</p>` : ''}<section class="tool-row" aria-label="Calendar tools"><button class="button primary" id="add-subscription">Add subscription</button><label class="file-button">Import CSV<input id="csv-input" type="file" accept=".csv,text/csv" /></label><button class="button" id="export-ics">Export ICS reminders</button><button class="button" id="export-csv">Export CSV</button><button class="button" id="backup">Encrypted backup</button></section>${dueSoon.length ? `<section class="attention" aria-labelledby="attention-title"><h2 id="attention-title">Review today</h2><p>${dueSoon.map((x) => `${esc(x.name)} (${money(x.amount, x.currency)})`).join(', ')}. Their review date has arrived.</p></section>` : ''}<section class="calendar" aria-labelledby="calendar-title"><div class="section-head"><h2 id="calendar-title">Renewal calendar</h2><span>${fmtDate(today)} to ${fmtDate(through)}</span></div>${occurrences.length ? occurrenceRows(occurrences) : emptyState()}</section><section class="inventory" aria-labelledby="inventory-title"><div class="section-head"><h2 id="inventory-title">Subscriptions</h2><span>${items.length} tracked</span></div>${items.length ? subscriptionRows() : ''}</section><section class="license" aria-labelledby="license-title"><h2 id="license-title">Pro license</h2><p>Use a paid license to show the 12-month forecast. The free calendar remains available.</p><form id="license-form"><label for="license-token">License token</label><div><input id="license-token" name="license" autocomplete="off" /><button class="button" type="submit">Verify license</button></div></form><a href="https://api.sociobot.in/api/v1/products/subscription-renewal-calendar/checkout">Buy Pro for $19</a></section></main>${footer()}`;
}
function emptyState() { return `<div class="empty"><h3>No subscriptions yet</h3><p>Your upcoming charges will appear here after you add a subscription or import a CSV.</p><button class="button primary" id="empty-add">Add your first subscription</button></div>`; }
function occurrenceRows(rows: Occurrence[]) { return `<div class="occurrence-list">${rows.map((o) => `<article class="occurrence ${o.decision}" tabindex="0"><time datetime="${o.dueOn}"><b>${fmtDate(o.dueOn)}</b><small>${relative(o.dueOn)}</small></time><div><h3>${esc(o.name)}</h3><p>Review ${fmtDate(o.reviewOn)} · Owner: ${esc(o.owner || 'Unassigned')}</p></div><strong>${money(o.amount, o.currency)}</strong><span class="decision">${o.decision}</span></article>`).join('')}</div>`; }
function subscriptionRows() { const unlocked = Boolean(localStorage.getItem('sb_license:subscription-renewal-calendar')); const total = money(allOccurrences(items, today, addDays(today, 365)).reduce((sum, item) => sum + item.amount, 0), items[0]?.currency || 'USD'); const forecast = unlocked ? `<section class="forecast"><h3>12-month forecast</h3><p>${total} scheduled across the next year.</p></section>` : `<section class="forecast locked"><h3>12-month forecast</h3><p>Pro adds a year-ahead total for planning.</p><a class="button" href="https://api.sociobot.in/api/v1/products/subscription-renewal-calendar/checkout">Buy Pro for $19</a></section>`; return `<div class="subscription-list">${items.map((x) => `<article><div><h3>${esc(x.name)}</h3><p>${money(x.amount, x.currency)} · ${x.frequency} · next cycle from ${fmtDate(x.startsOn)}</p><p>Owner: ${esc(x.owner || 'Unassigned')} · review ${x.reviewDays} days early · ${x.decision}</p></div><button class="icon-button" data-delete="${x.id}" aria-label="Delete ${esc(x.name)}">×</button></article>`).join('')}</div>${forecast}`; }
function legal(kind: 'privacy' | 'terms') {
  document.title = `${kind === 'privacy' ? 'Privacy' : 'Terms'} — Subscription Renewal Calendar`;
  const privacy = `<h1>Privacy that stays on your device.</h1><p>Renewal Ledger stores subscriptions in your browser’s IndexedDB. We do not run analytics, connect to banks, or send your list to our servers.</p><h2>Exports and backups</h2><p>CSV, ICS, and encrypted backup files download only when you ask. An encrypted backup uses your passphrase in this browser. Do not lose that passphrase.</p><h2>Deletion</h2><p>Delete individual subscriptions from the calendar. Clearing browser site data removes the rest. Demo data uses a separate browser database and is discarded when you leave.</p>`;
  const terms = `<h1>Terms for Subscription Renewal Calendar.</h1><p>This tool helps you plan recurring charges. It does not make financial decisions or guarantee that a provider will charge on a predicted date.</p><h2>Your responsibility</h2><p>Check renewal terms with each provider. Keep copies of your exported data and protect backup passphrases.</p><h2>Pro purchase</h2><p>Pro is a $19 one-time license, sold by Sociobot as merchant of record. Refunds and license status follow the checkout terms. Core data export remains free.</p>`;
  return `${header()}<main id="main" class="legal"><article>${kind === 'privacy' ? privacy : terms}</article></main>${footer()}`;
}
function notFound() { document.title = 'Page not found — Subscription Renewal Calendar'; return `${header()}<main id="main" class="legal"><article><h1>This page is not on the board.</h1><p>Use the calendar home to see upcoming renewals.</p><a class="button primary" href="/" data-route>Go to the renewal calendar</a></article></main>${footer()}`; }

function render() {
  currentRoute = location.pathname; let view = currentRoute === '/' ? landing() : (currentRoute === '/demo' || currentRoute === '/app') ? appView() : currentRoute === '/privacy' ? legal('privacy') : currentRoute === '/terms' ? legal('terms') : notFound();
  app.innerHTML = view; bind(); if (!firstRender) requestAnimationFrame(() => { const heading = document.querySelector<HTMLElement>('h1'); if (heading) { heading.tabIndex = -1; heading.focus({ preventScroll: true }); } }); firstRender = false;
}
async function persist() { try { await saveSubscriptions(space(), items); } catch { notice = 'Your browser blocked local storage. Allow site data, then try again.'; } }
function navigate(path: string) { history.pushState({}, '', path); isDemo = path === '/demo'; notice = ''; render(); }
function bind() {
  document.querySelectorAll<HTMLAnchorElement>('[data-route]').forEach((a) => a.addEventListener('click', (event) => { event.preventDefault(); navigate(a.getAttribute('href')!); }));
  document.querySelector('#reset-demo')?.addEventListener('click', async () => { items = sampleSubscriptions(); await persist(); notice = 'Demo reset with the original sample.'; render(); });
  document.querySelector('#start-real')?.addEventListener('click', async () => { await clearSubscriptions('demo:subscriptions'); isDemo = false; navigate('/app'); });
  document.querySelector('#add-subscription')?.addEventListener('click', showAddDialog); document.querySelector('#empty-add')?.addEventListener('click', showAddDialog);
  document.querySelector('#export-csv')?.addEventListener('click', exportCsv); document.querySelector('#export-ics')?.addEventListener('click', exportIcs); document.querySelector('#backup')?.addEventListener('click', encryptedBackup);
  document.querySelector('#csv-input')?.addEventListener('change', importCsv);
  document.querySelectorAll<HTMLButtonElement>('[data-delete]').forEach((button) => button.addEventListener('click', () => deleteSubscription(button.dataset.delete!)));
  document.querySelector('#license-form')?.addEventListener('submit', verifyLicense); document.querySelector('#undo-delete')?.addEventListener('click', undoDelete);
}
function showAddDialog() {
  const dialog = document.createElement('dialog'); dialog.className = 'dialog'; dialog.innerHTML = `<form method="dialog" id="add-form"><header><h2>Add a subscription</h2><button aria-label="Close">×</button></header><p>Use the original charge date. Weekly, monthly, and annual dates repeat from it.</p><div class="form-grid"><label>Name<input name="name" required /></label><label>Amount<input name="amount" type="number" min="0" step="0.01" required /></label><label>Currency<select name="currency"><option>USD</option><option>EUR</option><option>GBP</option><option>INR</option></select></label><label>Frequency<select name="frequency"><option value="monthly">Monthly</option><option value="weekly">Weekly</option><option value="annual">Annual</option></select></label><label>First charge<input name="startsOn" type="date" value="${today}" required /></label><label>Owner<input name="owner" required /></label><label>Review days early<input name="reviewDays" type="number" min="0" value="7" required /></label><label>Decision<select name="decision"><option value="review">Review</option><option value="keep">Keep</option><option value="cancel">Cancel</option></select></label><label class="wide">Note<input name="note" /></label></div><menu><button class="button" value="cancel">Cancel</button><button class="button primary" value="default">Save subscription</button></menu></form>`; document.body.append(dialog); dialog.showModal(); dialog.querySelector('#add-form')!.addEventListener('submit', async (event) => { event.preventDefault(); const f = new FormData(event.currentTarget as HTMLFormElement); const newItem: Subscription = { id: crypto.randomUUID(), name: String(f.get('name')).trim(), amount: Number(f.get('amount')), currency: String(f.get('currency')), frequency: String(f.get('frequency')) as Frequency, startsOn: String(f.get('startsOn')), owner: String(f.get('owner')).trim(), reviewDays: Number(f.get('reviewDays')), decision: String(f.get('decision')) as Decision, note: String(f.get('note')).trim() }; items.push(newItem); await persist(); notice = `${newItem.name} is now on the calendar.`; dialog.close(); dialog.remove(); render(); }); dialog.addEventListener('close', () => dialog.remove());
}
function parseCsv(text: string): Subscription[] {
  const lines = text.replace(/^\uFEFF/, '').trim().split(/\r?\n/); if (lines.length < 2) throw new Error('The CSV needs a heading row and at least one subscription.'); const headers = lines.shift()!.split(',').map((x) => x.trim().toLowerCase()); const required = ['name', 'amount', 'frequency', 'starts_on', 'owner']; if (required.some((x) => !headers.includes(x))) throw new Error('Use headings: name, amount, frequency, starts_on, owner.');
  return lines.map((line, index) => { const cells = line.split(',').map((x) => x.trim()); const get = (key: string) => cells[headers.indexOf(key)] || ''; const frequency = get('frequency').toLowerCase(); if (!['weekly', 'monthly', 'annual'].includes(frequency) || !/^\d{4}-\d{2}-\d{2}$/.test(get('starts_on')) || !Number.isFinite(Number(get('amount')))) throw new Error(`Row ${index + 2} has an invalid amount, frequency, or starts_on date.`); return { id: crypto.randomUUID(), name: get('name'), amount: Number(get('amount')), currency: get('currency') || 'USD', frequency: frequency as Frequency, startsOn: get('starts_on'), owner: get('owner'), reviewDays: Number(get('review_days') || 7), decision: (['keep', 'cancel', 'review'].includes(get('decision')) ? get('decision') : 'review') as Decision, note: get('note') }; });
}
async function importCsv(event: Event) { const input = event.currentTarget as HTMLInputElement; const file = input.files?.[0]; if (!file) return; try { const imported = parseCsv(await file.text()); items.push(...imported); await persist(); notice = `Imported ${imported.length} subscription${imported.length === 1 ? '' : 's'}.`; render(); } catch (error) { notice = error instanceof Error ? error.message : 'The CSV could not be read. Try again with the template headings.'; render(); } }
function exportCsv() { const csv = ['name,amount,currency,frequency,starts_on,owner,review_days,decision,note', ...items.map((x) => [x.name, x.amount, x.currency, x.frequency, x.startsOn, x.owner, x.reviewDays, x.decision, x.note || ''].map((v) => `"${String(v).replaceAll('"', '""')}"`).join(','))].join('\n'); download('renewal-ledger.csv', csv, 'text/csv'); notice = 'CSV exported.'; render(); }
function exportIcs() { const occurrences = allOccurrences(items, today, addDays(today, 365)); download('renewal-reminders.ics', icsReminders(items, today, addDays(today, 365)), 'text/calendar'); notice = `${occurrences.length} calendar reminders exported.`; render(); }
async function encryptedBackup() { const passphrase = prompt('Choose a passphrase for this backup. Keep it somewhere safe.'); if (!passphrase) return; const salt = crypto.getRandomValues(new Uint8Array(16)); const iv = crypto.getRandomValues(new Uint8Array(12)); const material = await crypto.subtle.importKey('raw', new TextEncoder().encode(passphrase), 'PBKDF2', false, ['deriveKey']); const key = await crypto.subtle.deriveKey({ name: 'PBKDF2', salt, iterations: 150000, hash: 'SHA-256' }, material, { name: 'AES-GCM', length: 256 }, false, ['encrypt']); const data = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, new TextEncoder().encode(JSON.stringify({ version: 1, subscriptions: items }))); const encode = (value: Uint8Array | ArrayBuffer) => btoa(String.fromCharCode(...new Uint8Array(value))); download('renewal-ledger.encrypted.json', JSON.stringify({ version: 1, salt: encode(salt), iv: encode(iv), data: encode(data) }), 'application/json'); notice = 'Encrypted backup exported. Keep its passphrase separate.'; render(); }
async function deleteSubscription(id: string) { const item = items.find((x) => x.id === id); if (!item || !confirm(`Delete ${item.name}? You can undo this once.`)) return; removed = item; items = items.filter((x) => x.id !== id); await persist(); notice = `${item.name} deleted.`; render(); }
async function undoDelete() { if (removed) { items.push(removed); await persist(); notice = `${removed.name} restored.`; removed = undefined; render(); } }
async function verifyLicense(event: Event) { event.preventDefault(); const token = String(new FormData(event.currentTarget as HTMLFormElement).get('license') || '').trim(); if (!token) { notice = 'Paste a license token, then verify it.'; render(); return; } localStorage.setItem('sb_license:subscription-renewal-calendar', token); notice = 'License saved on this device. It will verify when you are online.'; render(); try { const response = await fetch(`https://api.sociobot.in/api/v1/products/subscription-renewal-calendar/verify?license=${encodeURIComponent(token)}`); const result = await response.json() as { valid: boolean }; notice = result.valid ? 'Pro is active on this device.' : 'This license is not active. Check the token or buy Pro.'; render(); } catch { /* an offline user keeps the saved token for later verification */ } }

window.addEventListener('popstate', () => { isDemo = location.pathname === '/demo'; render(); });
async function start() { const params = new URLSearchParams(location.search); const incomingLicense = params.get('license'); if (incomingLicense) { localStorage.setItem('sb_license:subscription-renewal-calendar', incomingLicense); params.delete('license'); history.replaceState({}, '', `${location.pathname}${params.toString() ? `?${params}` : ''}`); notice = 'License saved. It will verify when you are online.'; } if (isDemo && location.pathname !== '/demo') history.replaceState({}, '', '/demo'); try { items = await readSubscriptions(space()); if (isDemo && !items.length) { items = sampleSubscriptions(); await persist(); } } catch { notice = 'Local storage is unavailable. Your changes may not persist.'; } if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined); render(); }
void start();
